### ISSUE TITLE
Warnings for undefined variable $mlid and undefined array keys.

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/bigmenu#5]
Difficult to know what is causing this. (EDIT - I wonder if the module looks for menu in the admin path in order to act, but doesn't exclude settings for each menu? - It seems to be quite intermittent)  I get it on config screens rather than a menu screen using bigmenu.  It doesn't appear to affect operation either of the module or of anything else.

![image](https://user-images.githubusercontent.com/20357797/209158987-074efd72-b778-4691-85d4-318be462e66e.png)

This is a dev site so I have all messages set to display currently.

Here is a location from one instance of this happening:
`admin/structure/menu/manage/management/bigmenu-customize/subform/1/js/bigmenu_overview_form/form-pNv5tnyU0HT_F7LRoLGT4VrX-lMb83TvuJGvblueft0`

Warning: Undefined variable $mlid in _bigmenu_overview_tree_form() (line 305 of /app/docroot/modules/contrib/bigmenu/bigmenu.admin.inc).
Warning: Undefined array key "" in _bigmenu_overview_tree_form() (line 305 of /app/docroot/modules/contrib/bigmenu/bigmenu.admin.inc).
Warning: Undefined array key "title" in _bigmenu_overview_tree_form() (line 305 of /app/docroot/modules/contrib/bigmenu/bigmenu.admin.inc).
Warning: Undefined array key "#markup" in _bigmenu_overview_tree_form() (line 305 of /app/docroot/modules/contrib/bigmenu/bigmenu.admin.inc).
Warning: Undefined variable $mlid in _bigmenu_overview_tree_form() (line 306 of /app/docroot/modules/contrib/bigmenu/bigmenu.admin.inc).
Warning: Undefined variable $mlid in _bigmenu_overview_tree_form() (line 305 of /app/docroot/modules/contrib/bigmenu/bigmenu.admin.inc).
Warning: Undefined variable $mlid in _bigmenu_overview_tree_form() (line 306 of /app/docroot/modules/contrib/bigmenu/bigmenu.admin.inc).

**Comment by bugfolder** [comment]
Weird that it appears on the Configure Menu tab; that tab shouldn't call any of the bigmenu functions at all.

Grasping at straws here, but I see the added XML sitemap fieldset (which probably does something with the menus) in your screen shot. If you disable that module, do you still see the errors?

**Comment by yorkshire-pudding** [comment]
I stopped getting it after I reported it. I've disabled and re-enabled XML sitemap and submodules and it's still not re-appearing.  I propose to close for now but I'll re-open if I get it again and can track down the cause.
